version: "3"
vars:
  NIX_CMD_BASE: nix develop . -c
tasks:
  ci:
    cmds:
      - task: lint
      - task: test
      - task: release-snapshot

  lint:
    cmds:
      - "{{.NIX_CMD_BASE}} golangci-lint run --enable-all"

  test:
    cmds:
      - "{{.NIX_CMD_BASE}} go test -v -race ./..."

  tidy:
    cmds:
      - go mod tidy
      - go mod vendor

  release:
    cmds:
      - "{{.NIX_CMD_BASE}} goreleaser release --clean"

  release-snapshot:
    cmds:
      - "{{.NIX_CMD_BASE}} goreleaser release --clean --snapshot"
