name: "release"
on:
  push:
    tags:
      - '**'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix develop . -c golangci-lint run --enable-all
      - run: nix develop . -c go test -v -race ./...
      - run: nix develop . -c skopeo --insecure-policy copy --dest-username ${{ github.actor }} --dest-password ${{ secrets.GITHUB_TOKEN }} docker-archive://$(nix build .#docker --print-out-paths) docker://ghrc.io/xsteadfastx/caddy-log-exporter:${{ github.ref_name }}
