name: "release"
on:
  push:
    tags:
      - '*'
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix develop . -c task ci-publish --GITHUB_USERNAME ${{ github.actor }} --GITHUB_PASSWORD ${{ secrets.GITHUB_TOKEN }} --GIT_TAG ${{ github.ref_name }}
